/*

    NOTES:
    - Model View Controller (MVC) Using Servlet & JSP:

    - Whenever a client sends a request say /request it goes to the Controller. Controller will call the View by sending a Model object(A model which will have the data). That Model will go to the View which wil replace all the blank texts, as View renders a layout. At this point what the client will get is the page
        - THe page is filled with the Model data and that data is generated by your Controller

        - Contoller is your servlet
        - View is your jsp
        - Model is Plain Old Java Object

    - Business processing should be done by your controller
    - Model is only for holding data. Never perform any operation on the Model object

    - N- Tier architecture
        - Controller is only for accepting the request and sending the response
        - If you want to perform any operation you need to create and extra class named "Service", your controller should basically be calling this Service class for processing

        - With this, when you send a request to the Controller, the Controller will call a Service class which is having methods and that service class will you the Object. Inside the Service class you have to write the JDBC steps, this way in future even if you decide to change the database, you dont have to change your controller, you will just have to change your service

        - If you working with DB we have one layer we need to keep in mind Data Access Object(DAO). If you want to interact with the database, the best way is using DAO classes

        - A request calls the controller, the controller calls the Service class, the Service class calls the DAO class

        - NOTE:
            - DAO and Service classes are not part of the MVC architecture
            - MVC is a just the Client, the Controller, the Model, the View

 */

public class Notes {
}
